project:
  type: website

website:
  title: "Anthony M. Diaz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
format:
  html:
    theme: superhero
    toc: true



